import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import type { EventSummary } from '@training/contracts';
import { useAuth } from '../auth/AuthContext.js';
import { ApiRequestError } from '../api/auth.js';
import { createEventQr, fetchAssessmentResults, fetchMyEvents, type AssessmentResults, type QrAccess } from '../api/events.js';

const publicAppUrl = (import.meta.env.VITE_PUBLIC_APP_URL || window.location.origin).replace(/\/$/, '');

const Results = ({ data }: { data: AssessmentResults }) => {
  const pre = new Map(data.submissions.filter((item) => item.phase === 'pre').map((item) => [item.nip, item]));
  const post = new Map(data.submissions.filter((item) => item.phase === 'post').map((item) => [item.nip, item]));
  const progress = [...new Set([...pre.keys(), ...post.keys()])].map((nip) => ({ nip, name: post.get(nip)?.name ?? pre.get(nip)?.name ?? nip, before: pre.get(nip)?.percentage ?? null, after: post.get(nip)?.percentage ?? null })).map((item) => ({ ...item, improvement: item.before != null && item.after != null ? item.after - item.before : null }));
  const weak = [...data.questionStats].filter((item) => item.wrong > 0).sort((a, b) => b.wrongPercentage - a.wrongPercentage).slice(0, 5);
  const table = (title: string, phase: string) => <section><h4 className="section-title">{title}</h4><div className="mt-2 grid gap-1">{data.submissions.filter((item) => item.phase === phase).map((item) => <div key={item.nip} className="flex justify-between border-b border-[#0A2942]/10 py-2 text-sm"><span>{item.name ?? item.nip}</span><strong>{item.percentage ?? 0}%</strong></div>)}</div></section>;
  return <section className="result-panel-open mt-5 border-t border-[#0A2942]/10 pt-5"><div className="grid gap-3 sm:grid-cols-3"><div className="bg-white p-4"><p className="eyebrow">Respons masuk</p><p className="metric">{data.submissions.length}</p></div><div className="bg-white p-4"><p className="eyebrow">Pre-test</p><p className="metric">{pre.size}</p></div><div className="bg-white p-4"><p className="eyebrow">Post-test</p><p className="metric">{post.size}</p></div></div><section className="mt-5"><h3 className="section-title">Kemajuan Pre-test ke Post-test</h3><div className="mt-2 grid gap-1">{progress.map((item) => <div key={item.nip} className="flex justify-between border-b border-[#0A2942]/10 py-2 text-sm"><span>{item.name}</span><strong className={item.improvement && item.improvement > 0 ? 'text-[#28704A]' : ''}>{item.improvement == null ? 'Belum lengkap' : `${item.improvement > 0 ? '+' : ''}${item.improvement}%`}</strong></div>)}</div></section><div className="mt-5 grid gap-6 sm:grid-cols-2">{table('Jawaban Pre-test', 'pre')}{table('Jawaban Post-test', 'post')}</div><section className="mt-5"><h3 className="section-title">Area Ketidakpahaman</h3><div className="mt-2 grid gap-2">{weak.map((item) => <div key={`${item.phase}-${item.number}`} className="border-l-2 border-[#B42318] bg-[#B42318]/5 p-2 text-sm"><strong>Soal {item.number} · {item.phase}</strong> · {item.wrongPercentage}% salah<p className="text-xs text-[#55697C]">{item.text}</p></div>)}</div></section></section>;
};

export const MyEvents = () => {
  const { session, signOut } = useAuth();
  const [events, setEvents] = useState<EventSummary[]>([]);
  const [message, setMessage] = useState('');
  const [qr, setQr] = useState<{ eventId: number; purpose: string; url: string } | null>(null);
  const [results, setResults] = useState<Record<number, AssessmentResults>>({});
  const [openResults, setOpenResults] = useState<number | null>(null);

  useEffect(() => { if (!session) return; fetchMyEvents(session.accessToken).then(setEvents).catch((error: unknown) => { if (error instanceof ApiRequestError && error.status === 401) signOut(); else setMessage(error instanceof ApiRequestError ? error.message : 'My Event gagal dimuat.'); }); }, [session, signOut]);
  const makeQr = async (eventId: number, purpose: QrAccess['purpose']) => { if (!session) return; try { const item = await createEventQr(session.accessToken, eventId, purpose); setQr({ eventId, purpose, url: `${publicAppUrl}${item.url}` }); setMessage(`QR ${purpose} dibuat.`); } catch (error) { const nextMessage = error instanceof ApiRequestError ? error.message : 'QR gagal dibuat.'; const shortcut = error instanceof ApiRequestError && ['TEST_NOT_CREATED', 'TEST_NO_QUESTIONS', 'TEST_NOT_PUBLISHED'].includes(error.code) ? ' Buka My Event > Buat / Publish Soal terlebih dahulu.' : ''; setMessage(`${nextMessage}${shortcut}`); } };
  const toggleResults = async (eventId: number) => { if (!session) return; if (openResults === eventId) return setOpenResults(null); setOpenResults(eventId); if (!results[eventId]) { try { const data = await fetchAssessmentResults(session.accessToken, eventId); setResults((current) => ({ ...current, [eventId]: data })); } catch (error) { setMessage(error instanceof ApiRequestError ? error.message : 'Hasil gagal dimuat.'); } } };

  return <><header className="border-b border-[#0A2942]/15 pb-5"><p className="eyebrow text-[#8A5A17]">Peran Pengisi Acara</p><h1 className="mt-1 text-3xl font-semibold text-[#0A2942]">My Event</h1><p className="mt-2 text-sm text-[#55697C]">Kelola QR assessment, absensi, soal, dan hasil peserta.</p></header>{message && <p className="mt-4 break-all text-sm text-[#8A5A17]">{message}</p>}<div className="my-events-grid mt-8 grid gap-5">{events.map((event) => <article key={event.id} className="my-event-card border border-[#0A2942]/15 bg-[#FAF8F3] p-5 sm:p-6"><Link to={`/events/${event.id}`}><p className="text-xs uppercase text-[#8A5A17]">{event.tgl}</p><h2 className="mt-1 text-xl font-semibold text-[#0A2942]">{event.judul}</h2><p className="mt-2 text-sm text-[#55697C]">Pengisi acara: <strong className="text-[#0A2942]">{event.pengisiAcara ?? 'Belum ditentukan'}</strong></p><p className="mt-1 text-xs text-[#55697C]">{event.pesertaCount} peserta</p></Link>{qr?.eventId === event.id && <section className="mt-4 flex items-center gap-4 border border-[#0A2942]/15 bg-white p-4"><img src={`https://quickchart.io/qr?text=${encodeURIComponent(qr.url)}&size=220`} alt={`QR ${qr.purpose}`} className="h-32 w-32" /><div className="min-w-0"><p className="text-sm font-semibold">QR {qr.purpose}</p><p className="mt-1 break-all text-xs text-[#55697C]">{qr.url}</p></div></section>}<div className="mt-5 grid grid-cols-2 gap-3 border-t border-[#0A2942]/10 pt-4 sm:grid-cols-4"><button type="button" onClick={() => makeQr(event.id, 'pre_test')} className="min-h-20 border bg-white p-3 text-left text-xs">QR Pre-test</button><button type="button" onClick={() => makeQr(event.id, 'post_test')} className="min-h-20 border bg-white p-3 text-left text-xs">QR Post-test</button><button type="button" onClick={() => makeQr(event.id, 'feedback')} className="min-h-20 border bg-white p-3 text-left text-xs">QR Feedback</button><button type="button" onClick={() => makeQr(event.id, 'attendance')} className="min-h-20 border border-[#8A5A17] bg-[#8A5A17]/5 p-3 text-left text-xs font-semibold text-[#8A5A17]">QR Absensi</button></div><div className="mt-4 flex flex-wrap gap-2"><Link to={`/my-events/${event.id}/questions`} className="bg-[#0A2942] px-3 py-2 text-xs font-semibold text-white">Buat Soal</Link><button type="button" onClick={() => toggleResults(event.id)} className="border border-[#0A2942] px-3 py-2 text-xs font-semibold">{openResults === event.id ? 'Tutup Hasil' : 'Lihat Jawaban'}</button></div>{openResults === event.id && results[event.id] && <Results data={results[event.id]} />}</article>)}</div></>;
};
